#! /usr/bin/perl -w
use strict;
use Geier;

Geier::init 0;
my $coala = new Geier();

#
# read infile and validate
#
open INFILE, "< data/test_ustva_unencrypted.xml" 
  or die "unable to open input file";
my $indata = "";
while(<INFILE>) { $indata .= $_ }
close INFILE or die;
die "unable to validate input" if $coala->validate($indata);

#
# read pincode
#
open PINFILE, "< data/TestHersteller_ELSTEstR.pin"
  or die "unable to open pincode file";
my $pincode = <PINFILE>; 
chop $pincode;
close PINFILE or die;

#
# sign it ...
#
my $signed = $coala->sign($indata, "data/TestHersteller_ELSTEstR.pfx", 
                          $pincode);
die "cannot sign document" unless $signed;

$signed =~ m/DigestValue>([^<]+)</
  or die "unable to extract digest value";
my $dv = $1;

#
# read expected digest value ...
#
open DVFILE, "< data/test_ustva_unencrypted_dsigvalue.b64"
  or die "unable to open digest-value file";
my $exp_dv = <DVFILE>;
chop $exp_dv;
close DVFILE or die;

die "expected digest value '$exp_dv' doesn't match calculated one: '$dv'"
  if($dv ne $exp_dv);

