#
# generate libgeier-ignores.i from geier.h header file
#
# Copyright (C) 2007 Stefan Siegl <stesie@brokenpipe.de>
# Licence: GPL, see www.taxbird.de
#

BEGIN {
    print "//";
    print "// DO NOT EDIT THIS FILE";
    print "// This file has been created by gen-ignores.awk " \
	"and will be overwritten.";
    print "//";
}

# ignore comments ...
/^ \* / { next }     

# avoid importing functions into the python module
/geier_.*\(/ {
    gsub(/^\*+/, "", $2);
    gsub(/\(.*/, "", $2);
    print "%rename(" substr($2, 6) ") " $2 ";";
}

# strip 'GEIER_' prefix from error codes
/GEIER_ERROR_/ {
    print "%rename(" substr($2, 7) ") " $2 ";";
}
